language: go

#  Workaround https://blog.travis-ci.com/2017-07-11-trusty-as-default-linux-is-coming?utm_source=web&utm_medium=banner&&utm_campaign=trusty-default
#  Goveralls hangs and cannot send data on dist:trusty.
dist: precise              

go:
  - 1.8.x
  - tip
  # - master  the same as 'tip'

before_install:
  - go get github.com/mattn/goveralls
  
script:
  - make
  - $HOME/gopath/bin/goveralls -service=travis-ci

#install:
#  - go get -u github.com/lisitsky/go-site-search-string

#script:
#  - make test


