language: go

go:
  - 1.8.x
  - tip
  # - master  the same as 'tip'

before_install:
  - go get github.com/mattn/goveralls
  
script:
  - make
  - $HOME/gopath/bin/goveralls -service=travis-ci

#install:
#  - go get -u github.com/lisitsky/go-site-search-string

#script:
#  - make test


